require 'rest-client'
require 'json'

Brewery.destroy_all
Beer.destroy_all
Customer.destroy_all
Favorite.destroy_all

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

url = "https://api.openbrewerydb.org/breweries?per_page=50"
resp = RestClient.get(url)

data = JSON.parse(resp)


data.each do |brewery|
    Brewery.create(name: brewery["name"], state: brewery["state"], brewery_type: brewery["brewery_type"], website_url: brewery["website_url"])
end


Beer.create(name: "Vanillaphant Porter", brewery_id: 1 )
Beer.create(name: "Battlefield IPA", brewery_id: 1 )
Beer.create(name: "Miss Fancy's Tripel", brewery_id: 1 )
Beer.create(name: "TrimTab IPA", brewery_id: 2 )
Beer.create(name: "Paradise Now (Raspberry Berliner Weisse)", brewery_id: 2 )
Beer.create(name: "Pillar To Post", brewery_id: 2 )
Beer.create(name: "Rebellion", brewery_id: 3 )
Beer.create(name: "Belgian White Ale", brewery_id: 3 )
Beer.create(name: "Midnight Special", brewery_id: 3 )
Beer.create(name: "Frontiersman IPA", brewery_id: 4 )
Beer.create(name: "Mat Maid", brewery_id: 4 )
Beer.create(name: "Hatcher Pass", brewery_id: 4 )
Beer.create(name: "Helles Golden Lager", brewery_id: 5 )
Beer.create(name: "Winter Warmer", brewery_id: 5 )
Beer.create(name: "Humpy's Saison", brewery_id: 5 )
Beer.create(name: "Naughty Naranja", brewery_id: 6 )
Beer.create(name: "Weapons Check", brewery_id: 6 )
Beer.create(name: "Baya Gose", brewery_id: 6 )
Beer.create(name: "Western Lager", brewery_id: 7 )
Beer.create(name: "Saison", brewery_id: 7 )
Beer.create(name: "HopStorm® IPA", brewery_id: 8 )
Beer.create(name: "Jeremiah Red", brewery_id: 8 )
Beer.create(name: "Piranha Pale Ale", brewery_id: 8 )
Beer.create(name: "Admiration IPA", brewery_id: 9 )
Beer.create(name: "Vanilla Infused Porter (VIP)", brewery_id: 9 )
Beer.create(name: "Baja Sol", brewery_id: 9 )
Beer.create(name: "Dragoon IPA", brewery_id: 10 )
Beer.create(name: "Stronghold Session", brewery_id: 10 )
Beer.create(name: "Santa Cruz'R", brewery_id: 10 )
Beer.create(name: "Sunset Amber Ale", brewery_id: 11 )
Beer.create(name: "Black Iron IPA", brewery_id: 11 )
Beer.create(name: "Grand Canyon Expedition Wheat", brewery_id: 11 )
Beer.create(name: "Desert Magic IPA", brewery_id: 12 )
Beer.create(name: "Full Moon", brewery_id: 12 )
Beer.create(name: "HavaBlue", brewery_id: 12 )
Beer.create(name: "McRichter Paleworks", brewery_id: 13 )
Beer.create(name: "Criminal Mischief", brewery_id: 13 )
Beer.create(name: "Hot Fuzz", brewery_id: 13 )
Beer.create(name: "JuicyJack", brewery_id: 14 )
Beer.create(name: "MoonJuice", brewery_id: 14 )
Beer.create(name: "HopShock", brewery_id: 14 )
Beer.create(name: "Sound of Freedom IPA", brewery_id: 15 )
Beer.create(name: "Northeast X Southwest", brewery_id: 15 )
Beer.create(name: "Suncast IPA", brewery_id: 15 )
Beer.create(name: "Spellbinder", brewery_id: 16 )
Beer.create(name: "Jomax", brewery_id: 16 )
Beer.create(name: "Wrenovation", brewery_id: 16 )
Beer.create(name: "Dirty Sally", brewery_id: 17 )
Beer.create(name: "Troubled Horse Porter", brewery_id: 17 )
Beer.create(name: "Claw Hammer", brewery_id: 17 )
Beer.create(name: "Pig Trail Porter", brewery_id: 18 )
Beer.create(name: "Two Term Double IPA", brewery_id: 18 )
Beer.create(name: "Dogtown Brown", brewery_id: 18 )
Beer.create(name: "Love Honey Bock", brewery_id: 19 )
Beer.create(name: "Crystal State Rockhound IPA", brewery_id: 19 )
Beer.create(name: "Day Drinker Belgian Blonde", brewery_id: 19 )
Beer.create(name: "1000K IPA", brewery_id: 20 )
Beer.create(name: "My Sweet Mtn. Home Stout", brewery_id: 20 )
Beer.create(name: "Buffalo Blonde Ale", brewery_id: 20 )
Beer.create(name: "Plundered Abby Tripel", brewery_id: 21 )
Beer.create(name: "Sliepnir's Kick Maple Porter", brewery_id: 21 )
Beer.create(name: "Ayla's Amber Ale", brewery_id: 21 )
Beer.create(name: "Islay Hill IPA", brewery_id: 22 )
Beer.create(name: "Cabrillo. Peak Amber", brewery_id: 22 )
Beer.create(name: "Cerro San Luis Imperial Stout", brewery_id: 22 )
Beer.create(name: "Boss Pour IPA", brewery_id: 23 )
Beer.create(name: "BA Brick in Yo Face", brewery_id: 23 )
Beer.create(name: "Candy Cane Ice Cream Cake", brewery_id: 23 )
Beer.create(name: "Maui Waui IPA", brewery_id: 24 )
Beer.create(name: "Hella Hoppy", brewery_id: 24 )
Beer.create(name: "Juice Above the Clouds", brewery_id: 24 )
Beer.create(name: "Gold Digger IPA", brewery_id: 25 )
Beer.create(name: "PU240 Imperial IPA", brewery_id: 25 )
Beer.create(name: "ZZ Hop Triple IPA", brewery_id: 25 )
Beer.create(name: "Tomahawk Double IPA", brewery_id: 26 )
Beer.create(name: "Rita Red", brewery_id: 26 )
Beer.create(name: "Set Sail IPA", brewery_id: 26 )
Beer.create(name: "Racer 5 IPA", brewery_id: 27 )
Beer.create(name: "Hop Rod Rye", brewery_id: 27 )
Beer.create(name: "Red Rocket Ale", brewery_id: 27 )
Beer.create(name: "Grizzly Paw", brewery_id: 28 )
Beer.create(name: "Three Hours From Nowhere", brewery_id: 28 )
Beer.create(name: "Evil Ben Black IPA", brewery_id: 28 )
Beer.create(name: "Sparkle Pony", brewery_id: 29 )
Beer.create(name: "Nectar of Life", brewery_id: 29 )
Beer.create(name: "Witless Zombie", brewery_id: 29 )
Beer.create(name: "Excavator Doppel Bock", brewery_id: 30 )
Beer.create(name: "E.P.A.", brewery_id: 30 )
Beer.create(name: "Sequoia Red", brewery_id: 30 )
Beer.create(name: "Many Moons", brewery_id: 33 )
Beer.create(name: "Coconut Moons", brewery_id: 33 )
Beer.create(name: "Oatie Oats India Pale Ale", brewery_id: 33 )
Beer.create(name: "Agua Fresca", brewery_id: 34 )
Beer.create(name: "Fruit Cup", brewery_id: 34 )
Beer.create(name: "Café con Leche", brewery_id: 34 )
Beer.create(name: "Beautiful View", brewery_id: 35 )
Beer.create(name: "Guerita", brewery_id: 35 )
Beer.create(name: "Aztec Princess", brewery_id: 35 )
Beer.create(name: "Table of Brotherhood", brewery_id: 36 )
Beer.create(name: "Goods From The Woods", brewery_id: 37 )
Beer.create(name: "Woke AF Hazy IPA", brewery_id: 37 )
Beer.create(name: "McSteamy", brewery_id: 37 )
Beer.create(name: "Floyd IPA", brewery_id: 38 )
Beer.create(name: "Cloverdale Ale", brewery_id: 38 )
Beer.create(name: "Oatmeal Raisin Cookie Stout", brewery_id: 38 )
Beer.create(name: "1903 Lager", brewery_id: 39 )
Beer.create(name: "Heavenly Hefe", brewery_id: 39 )
Beer.create(name: "El Prieto Sour Black Ale", brewery_id: 39 )
Beer.create(name: "Lady Roja", brewery_id: 41 )
Beer.create(name: "Bridges", brewery_id: 41 )
Beer.create(name: "Aurantia", brewery_id: 41 )
Beer.create(name: "Hoppy Salvation", brewery_id: 42 )
Beer.create(name: "O'Beardsley's Stout", brewery_id: 42 )
Beer.create(name: "Golden Nektar", brewery_id: 42 )
Beer.create(name: "10:45 To Denver", brewery_id: 43 )
Beer.create(name: "Glitz And Glam", brewery_id: 43 )
Beer.create(name: "Civility", brewery_id: 43 )
Beer.create(name: "Lazy Day IPA", brewery_id: 44 )
Beer.create(name: "Midnight Express", brewery_id: 44 )
Beer.create(name: "Redlands Nights", brewery_id: 44 )
Beer.create(name: "King Citra", brewery_id: 45 )
Beer.create(name: "Hazy Train", brewery_id: 45 )
Beer.create(name: "Galaxy Juice", brewery_id: 45 )
Beer.create(name: "Villager", brewery_id: 46 )
Beer.create(name: "KSA", brewery_id: 46 )
Beer.create(name: "Animal IPA", brewery_id: 46 )
Beer.create(name: "Dream Catcher", brewery_id: 47 )
Beer.create(name: "Citro Haze", brewery_id: 47 )
Beer.create(name: "Basic AF", brewery_id: 47 )
Beer.create(name: "Conveyor IPA", brewery_id: 48 )
Beer.create(name: "Cogzilla Double IPA", brewery_id: 48 )
Beer.create(name: "Burned And Blackened Smoked Porter", brewery_id: 48 )
Beer.create(name: "Heritage Honey Ale", brewery_id: 49 )
Beer.create(name: "Cold Brew Coffee Stout", brewery_id: 49 )
Beer.create(name: "Eureka! IPA", brewery_id: 49 )
Beer.create(name: "Wheel's Up", brewery_id: 50 )
Beer.create(name: "Betty IPA", brewery_id: 50 )
Beer.create(name: "Easy Glider", brewery_id: 50 )

##should name be username if we do beer-a-dex? can we create a leaderboard?
Customer.create(name: "Steven Ross")
Customer.create(name: "Andrew de la Vega")
Customer.create(name: "Craig")
Customer.create(name: "Sean")
Customer.create(name: "Yoan Elon Space BBQ Musk Ante")


Favorite.create(beer: Beer.all.sample, customer: Customer.first)
Favorite.create(beer: Beer.all.sample, customer: Customer.third)

